In [1]:
!pip install tensorflow

You should consider upgrading via the 'python -m pip install --upgrade pip' command.


In [2]:
import tensorflow as tf

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\hp\appdata\local\pr

# Tensor Data Structure


In [ ]:
# What is Tensors:
Tensors are used as the basic data structures in TensorFlow language. Tensors represent
the connecting edges in any flow diagram called the Data Flow Graph. Tensors are defined
as multidimensional array or list.

Tensors are identified by the following three parameters:
    
Rank:
Unit of dimensionality described within tensor is called rank. It identifies the number of
dimensions of the tensor. A rank of a tensor can be described as the order or n-dimensions
of a tensor defined.

Shape:
The number of rows and columns together define the shape of Tensor.

Type:
Type describes the data type assigned to Tensor’s elements.

A user needs to consider the following activities for building a Tensor:
1- Build an n-dimensional array
2- Convert the n-dimensional array.

Check this link:
https://i.ibb.co/d2nhmRy/tesnors.png
https://i.ibb.co/Lt4GN3f/tesnors.png


# One dimensional Tensor

In [5]:
import numpy as np
tensor_1d = np.array([1.3, 1, 4.0, 23.99])
print(tensor_1d)
# The indexing of elements is same as Python lists. The first element starts with index of 0;
# to print the values through index, all you need to do is mention the index number.

print(tensor_1d[0])
print(tensor_1d[2])


[ 1.3   1.    4.   23.99]
1.3
4.0


# Two dimensional Tensors

In [6]:
# Sequence of arrays are used for creating “two dimensional tensors”.
import numpy as np
tensor_2d=np.array([(1,2,3,4),(4,5,6,7),(8,9,10,11),(12,13,14,15)])
print(tensor_2d)
print(tensor_2d[3][2])

[[ 1  2  3  4]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
14


# Tensor Handling and Manipulations

In [7]:
import tensorflow as tf
import numpy as np
matrix1 = np.array([(2,2,2),(2,2,2),(2,2,2)],dtype='int32')
matrix2 = np.array([(1,1,1),(1,1,1),(1,1,1)],dtype='int32')
print (matrix1)
print (matrix2)
matrix1 = tf.constant(matrix1)
matrix2 = tf.constant(matrix2)
matrix_product = tf.matmul(matrix1, matrix2)
matrix_sum = tf.add(matrix1,matrix2)
matrix_3 = np.array([(2,7,2),(1,4,2),(9,0,2)],dtype='float32')
print (matrix_3)
matrix_det = tf.matrix_determinant(matrix_3)
with tf.Session() as sess:
 result1 = sess.run(matrix_product)
 result2 = sess.run(matrix_sum)
 result3 = sess.run(matrix_det)
print (result1)
print (result2)
print (result3)

"""We have created multidimensional arrays in the above source code. Now, it is important
to understand that we created graph and sessions, which manage the Tensors and
generate the appropriate output. With the help of graph, we have the output specifying
the mathematical calculations between Tensors."""

c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:493: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:494: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
c:\users\hp\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\framework\dtypes.py:495: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
c:\users\hp\appdata\local\pr

[[2 2 2]
 [2 2 2]
 [2 2 2]]
[[1 1 1]
 [1 1 1]
 [1 1 1]]
[[2. 7. 2.]
 [1. 4. 2.]
 [9. 0. 2.]]
[[6 6 6]
 [6 6 6]
 [6 6 6]]
[[3 3 3]
 [3 3 3]
 [3 3 3]]
55.999992
